version: '3'
services:
  app_vet:
    build: clinica_veterinaria
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://34zzm.h.filess.io:3307/testeus_clockleft?serverTimezone=UTC
      DB_USER_NAME: testeus_clockleft
      DB_PASSWORD: 58fa4d4cfda8265ef7831369bbac3414ad97f932
    restart: always